### ISSUE TITLE
How to Correctly Assign Attributes to Session.Attributes

### ISSUE THREAD

**Issue by Caoimhin89** [ericdaugherty/alexa-skills-kit-golang#10]
Hi, I'm having trouble assigning session attributes.

In OnSessionCreated:

```
sessionAttributes := make(map[string]interface{})
session.Attributes.String = sessionAttributes
```
Later, in OnIntent:

```
session.Attributes.String["driveway"] = request.Intent.Slots["DrivewayType"].Value
session.Attributes.String["product"] = request.Intent.Slots["Product"].Value
```

But I get this error in my Lambda function output:

```
  "errorMessage": "assignment to entry in nil map",
  "errorType": "plainError",
```

**Comment by ericdaugherty** [comment]
Kevin,

You can't count on OnSessionCreated getting called before OnIntent each time.  In OnIntent, you should check the session.Attributes.String value and initialize if needed before setting.

OnSession is only called if RequestEnvelope.Session.New is set by the caller.

**Comment by koblas** [comment]
Since I was just looking at some code yesterday, I noticed that Session variables shouldn't work at all in the current codebase.

Specifically. if you read the Alexa AP for the [response parameters](https://developer.amazon.com/docs/custom-skills/request-and-response-json-reference.html#response-parameters) you noticed that you have to return the updated session attributes.

When you look at the code in alexa.go that field of the responseEnv is never populated with the session information.  In addition the responseEnvelope is not available to the handlers.

**Comment by ericdaugherty** [comment]
David,

Good catch. I updated ProcessRequest to copy any parameters from the Session into the ResponseEnv before returning.

This should also help your initial issue Kevin.
